name: webelements
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  js: ^0.7.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/js/
  uses-material-design: true
